services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "5555:5555"  # This allows Prisma Studio to be accessed
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
    command: npm run dev

volumes:
  node_modules: