version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile     # your single-stage Dockerfile
    working_dir: /app
    volumes:
      - .:/app                   # mount your project for hot-reload
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"              # map container → host
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
    command: npm run dev         # ensure 'next dev' runs inside the container

volumes:
  node_modules:                  # named volume to persist container-installed deps